version: '3.8'

networks:
  pizza-network:
    external: true

services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: user_service
#    ports:
#      - "5435:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pizza-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pizza-network

  order-service:
    build:
      context: .  # Path to the directory containing the Dockerfile for user-service
      dockerfile: Dockerfile  # Specify Dockerfile if it's not named 'Dockerfile'
    container_name: order-service
    restart: always
    env_file:
      - .env
    networks:
      - pizza-network
#    depends_on:
#      - postgres
    ports:
      - "8004:8000"